### ISSUE TITLE
I plan to contribute codes into  torodb, to add distributed cache like hazelcast into torodb

### ISSUE THREAD

**Issue by theseusyang** [torodb/torodb#107]
Hi Team,

I plan to contribute codes into  torodb, to add distributed cache like hazelcast into torodb.
because the lack MPP ablility in Postgres,  I want add hazelcast into torodb core, How to start it?

thank you!
theseus yang

**Comment by gavioto** [comment]
Disclaimer: I'm not realted with ToroDB developers or used it, so my reply is based only on my own knowledge of database theory and software architecture.

I think you **don't need nothing special** as ToroDb is a MongoDB replacement you should use all the tools that works with a mongo database (in theory) http://blog.hazelcast.com/hazelcast-mongodb/

On the other hand, using hazelcast depends of the layer of hazelcast you wants to use. 

Are you meaning to use ToroDB as a backend for Hazelcast persistence? I that case I think [you could use it as a mongodb persistence layer for hazelcast](http://blog.hazelcast.com/for-mongodb-developers/), but with improved ACID consistency

![image](https://cloud.githubusercontent.com/assets/2454642/20497259/c9c7f04e-b028-11e6-96b8-646cd70557ff.png)

**Comment by ahachete** [comment]
Thank you @theseusyang for your proposal and @gavioto for your suggestions. @theseusyang I think the ideal place for this discussion is the mailing list, where you already started a thread and I responded there. Let's please follow-up there: https://groups.google.com/forum/#!topic/torodb-dev/Q7Rw1lKYJp0

Anyway, as @gavioto commented, there are two different approaches: a distributed cached on top of ToroDB or using Hazelcast (or other, but I believe Hazelcast is an amazing option) as an *internal* cache for scaling out ToroDB. I believe @theseusyang referred to the latter.

If so, the code needs some understanding of ToroDB internals. In particular, you should be looking at some modules like torodb-core and the torodb metacache information. However, as stated in the mailing list, both have had very significant changes that will be pushed in a few days to the Github. So I'd suggest you to signup at https://www.torodb.com to be alert of the coming news, and keep in touch with us to plan this work. We will be in contact @theseusyang as we discussed already by email.

I will be closing the issue now as it will be discussed in the mailing list. Thanks for your help.
