### ISSUE TITLE
What is the recommended way to set this up in front of an AWS RDS?

### ISSUE THREAD

**Issue by shamoons** [torodb/torodb#15]
Will I have to spin up an instance JUST to host the ToroDB which will connect to my RDS? Seems like an expensive way to go about it.

**Comment by ahachete** [comment]
If you are using RDS as the PostgreSQL instance, sure you will need another instance to host ToroDB. However, you could collocate ToroDB with your app.

If you are not using RDS, you could (and you will get better performance) if you host PostgreSQL and ToroDB on the same host.
