### ISSUE TITLE
BSON regex object support

### ISSUE THREAD

**Issue by okapies** [torodb/torodb#18]
torodb throws an exception `"Arguments of java.util.regex.Pattern type are not supported yet"` when BSON queries contain regex objects.

https://github.com/torodb/torodb/blob/d94b5b89bcab38e2b21ebf94310109cacd40a153/kvdocument/mongo-converter/src/main/java/com/torodb/kvdocument/conversion/mongo/MongoValueConverter.java#L122-123

(I want to use torodb with [Let's Chat](https://github.com/sdelements/lets-chat), but it fails in migration phase on initial startup because of this problem.)

**Comment by ahachete** [comment]
Hi Yuta!

Thank you for trying ToroDB with Let's Chat, and for raising this issue. We (obviously) knew it isn't implemented, but having users like you raising issues for features needed helps us give them more priority.

We have started working on it, although it's a non trivial patch. We will hopefully come back soon.

**Comment by okapies** [comment]
:+1:

**Comment by okapies** [comment]
I think RDS-backed Let's Chat is very cool because of its low maintenance cost and simplicity of operation.

**Comment by ahachete** [comment]
Sure, it would be cool!

We're working on a patch right now. It will be ready, hopefully, soon. Stay tuned!

**Comment by ahachete** [comment]
Hi! Good news. It looks like we have already added support for this. In a few hours we will be pushing out v0.22 which will have support for $regex, among some other bug fixes. Please try it out and reopen this issue if for some reason it doesn't work correctly for you.

Feel free to join the torodb-dev mailing list (https://groups.google.com/forum/#!forum/torodb-dev) to discuss further issues.

Thank you!

**Comment by okapies** [comment]
Great! Thanks so much.
