### ISSUE TITLE
Link to latest (0.23) download is broken

### ISSUE THREAD

**Issue by zarmack** [torodb/torodb#25]
Hi,
I'm triing to download the latest version using the link at the README.md file and doesn't work
http://maven.torodb.com/jar/com/torodb/torodb/0.23/torodb.jar

Regards,
zarmack

**Comment by ahachete** [comment]
On 13/11/15 11:17, Zarmack Tanen wrote:
>
> Hi,
> I'm triing to download the latest version using the link at the 
> README.md file and doesn't work
> http://maven.torodb.com/jar/com/torodb/torodb/0.23/torodb.jar
>
> Regards,
> zarmack
>
>

     Hey, thanks for the warning. Fixed. You should be able to download 
and test it now. Sorry for the inconvenience!

     Cheers,

     Álvaro


-- 
Álvaro Hernández Tortosa


-----------
8Kdata
