### ISSUE TITLE
Add support for more mongo commands

### ISSUE THREAD

**Issue by maxamel** [torodb/torodb#7]
As requested, new issue regarding adding support of commands:
list Databases, users info, ping.

**Comment by gortiz** [comment]
list databases and ping are implemented since v0.20 but we do not support user management yet

**Comment by csalazart** [comment]
For Mongo Commands it is not a MongoDB power shell soo this a Ineterface for conect mongoDB drivers and put data on relations DB, 
I try severals commands like 
sort, not Working..
createIndex -> Not working ON Array fields. 
proyections fields on find clause, not working too 

i have severasl pics and comments about this. =P

**Comment by ahachete** [comment]
Hi, Carlos Alberto.

There are many comments here, we may be splitting it into several different issues which might be implemented at different stages.

Would you mind opening a broader discussion at the developers' mailing list? (https://groups.google.com/forum/#!forum/torodb-dev). Thank you!

Álvaro
