### ISSUE TITLE
DateTimeParseException - from nodejs sails application

### ISSUE THREAD

**Issue by andreabat** [torodb/torodb#90]
Hello,
I'm developing a webapplicaton using nodejs ( and specifically sailjs). Whenever I create a new document with dates ( sailsjs adds createdAt and updatedAt) I get a DateTimeParseException error
for example,
`com.torodb.torod.core.exceptions.ToroRuntimeException: org.threeten.bp.format.DateTimeParseException: Text '2016-05-11T14:30:00' could not be parsed at index 19`.

Everything works fine if i use a "regular" mongod.

Thank you

**Comment by andreabat** [comment]
Forgot the version: 0.40-alpha3

**Comment by gortiz** [comment]
If I remmember correctly, that is an issue that is resolved on the devel
branch. I think we will release a new version on master soon, but you can
try the devel branch right now if you want

2016-05-13 14:54 GMT+02:00 Andrea Batazzi <notifications@github.com>:

**Comment by teoincontatto** [comment]
Hi @andreabat,

It would be really useful the full stack trace and/or a little test using mongo shell that would permit us to localize and reproduce the issue so it can be fixed.

**Comment by ahachete** [comment]
@andreabat, it was fixed by this commit: https://github.com/torodb/torodb/commit/dd01cda1708f14422e95801fa66040f2f0509372 Please try devel branch. As @gortiz mentioned, it will be soon wrapped in a new release. Let us know if it works for you. Thanks

**Comment by gortiz** [comment]
I close this issue, as it does not apply to the new version
